### ISSUE TITLE
Duplicate Keys

### ISSUE THREAD

**Issue by mdaines-r7** [rapid7/rex#2]
`lib/rex/proto/smb/exceptions.rb` has two duplicate keys:
Line 12:

``` ruby
  @@errors = {
    0x00000000 => "STATUS_SUCCESS",
    0x00000000 => "STATUS_WAIT_0",
```

Line 18:

``` ruby
  @@errors = {
...
    0x00000080 => "STATUS_ABANDONED",
    0x00000080 => "STATUS_ABANDONED_WAIT_0",
```

Similar problem in `lib/rex/proto/http/server.rb`:
Line 84:

``` ruby
  ExtensionMimeTypes =
    {
...
      "jpeg"  => "image/jpeg",
      "jpeg"  => "image/jpeg",
```

**Comment by hdm** [comment]
I believe this has been fixed upstream as of last week as well. I will cut a new Rex gem soon,

**Comment by erran-r7** [comment]
@hmoore-r7 these warning still exist on `master`. The current files:
- [ ] https://github.com/rapid7/rex/blob/1b0af557/lib/rex/proto/smb/exceptions.rb#L11-L12
- [ ] https://github.com/rapid7/rex/blob/1b0af557/lib/rex/proto/smb/exceptions.rb#L17-L18
- [ ] https://github.com/rapid7/rex/blob/b70b594a/lib/rex/proto/http/server.rb#L83-L84

**Comment by erran-r7** [comment]
@hmoore-r7 just spoke to Tod and Lance. I understand what you meant by upstream now. I'm just going to remove `rex` as a dependency from `nexpose-client`. We're barely utilizing it and unless we're using the upstream version then I can't see any benefit from "sharing" this code between r7 projects.

**Comment by hdm** [comment]
Got it, thanks!

**Comment by hdm** [comment]
I'll cut a new rex gem with this change once https://github.com/rapid7/metasploit-framework/pull/4848 is merged.

**Comment by erran-r7** [comment]
This is fixed in https://github.com/rapid7/metasploit-framework/commit/ab4a41695 apparently. Not sure they're in the latest release. Testing now.  rapid7/metasploit-framework#4848 got closed though.

**Comment by erran-r7** [comment]
@todb-r7 @hmoore-r7 Those changes are not in the `2.0.7` release of the gem. It looks like all we need is a version bump and gem release with the duplicate key changes. Since we just closed 4848 let's release with the 2.2.x fixes.

```
/Users/ecarey/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rex-2.0.7/lib/rex/proto/http/server.rb:83: warning: duplicated key at line 84 ignored: "jpeg"
/Users/ecarey/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rex-2.0.7/lib/rex/proto/smb/exceptions.rb:11: warning: duplicated key at line 12 ignored: 0
/Users/ecarey/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rex-2.0.7/lib/rex/proto/smb/exceptions.rb:17: warning: duplicated key at line 18 ignored: 128
```

It's driving me pretty crazy at this point. How can we get those changes released?

**Comment by hdm** [comment]
Since https://github.com/rapid7/metasploit-framework/pull/4848 was delayed, this fell off my radar. I'll cut a new gem now.

**Comment by hdm** [comment]
rex-2.0.8 has been released.

**Comment by erran-r7** [comment]
Great, thank you.
